Simple Program

In [7]:
base = 5.45
height = 10.3
area = 0.5 * base * height
print("Area Of The Triangle = ", round(area, 2))

Area Of The Triangle =  28.07


Input, Casting And If-Else Statement 

In [8]:
num = int((input("Enter A Number: ")))
if num % 2 == 0:
    print(str(num) + " Is An Even Number!")
else:
    print(str(num) + " Is An Odd Number!")

2 Is An Even Number!


Nest If-Else Statements

In [9]:
indianDishes = ["Samosa", "Daal", "Naan"]
chineseDishes = ["Egg Roll", "Pot Sticker", "Fried Rice"]
italianDishes = ["Pizza", "Pasta", "Risotto"]

dishInput = input("Enter The Dish: ")

if dishInput in indianDishes:
    print(dishInput + ": Indian Dish")
elif dishInput in chineseDishes:
    print(dishInput + ": Chinese Dish")
elif dishInput in italianDishes:
    print(dishInput + ": Italian Dish")
else:
    print("Dish Not In Menu")


Pizza: Italian Dish


For Loop In Range

In [10]:
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


For Loop With len Funciton

In [11]:
expenses = [2345, 1234, 3454, 5466]
for i in expenses:
    print(i)
print("Length Of Expenses : " + str(len(expenses)))

2345
1234
3454
5466
Length Of Expenses : 4


For Loop With Range And len Function

In [12]:
expenses = [2345, 1234, 3454, 5466]
total = 0
for i in range(len(expenses)):
    print("Month: " + str(i + 1) + ", Expense: " + str(expenses[i]))
    total += expenses[i]
print("Total Expense = " + str(total))


Month: 1, Expense: 2345
Month: 2, Expense: 1234
Month: 3, Expense: 3454
Month: 4, Expense: 5466
Total Expense = 12499


For Loop With Step Counter

In [13]:
for i in range(1, 6, 2):
    print(i*i)

1
9
25


While Loop

In [14]:
i = 1
while i <= 5:
    print(i)
    i += 1


1
2
3
4
5


Functions In Python

In [15]:
myExpense = [123, 456, 789, 1123]
yourExpense = [234, 567, 890]

def expenseCalculator(expense):
    total = 0
    for i in range(len(expense)):
        total += expense[i]
    return total

print("myExpense = " + str(expenseCalculator(myExpense)))
print("yourExpense = " + str(expenseCalculator(yourExpense)))

myExpense = 2491
yourExpense = 1691


Dictionary And Tuples

In [16]:
employee = {"employeeId": 3976, "name": "Mayur Pai",
            "email": "mbantwal@galaxe.com"}

for k, v in employee.items():
    print(k + ": " + str(v))

for key in employee:
    print(key + ": " + str(employee[key]))

print("name" in employee)
print("Mayur Pai" in employee)
print(employee)

point = (3, 4)
print(point)
print(point[1])


employee = (3976, "Mayur Pai", "mbantwal@galaxe.com")
print("Mayur Pai" in employee)
print(employee[2])

employeeId: 3976
name: Mayur Pai
email: mbantwal@galaxe.com
employeeId: 3976
name: Mayur Pai
email: mbantwal@galaxe.com
True
False
{'employeeId': 3976, 'name': 'Mayur Pai', 'email': 'mbantwal@galaxe.com'}
(3, 4)
4
True
mbantwal@galaxe.com


Module List

In [17]:
import math

dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'cbrt',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'exp2',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

Modules In Python

In [18]:
# import sys 
# # Add The Path Where The Module Is Situated
# sys.path.append("C:\Users\mbantwal\GitLab\Gx\Python-Workspace")
# # Import The Function That You Wish To Use
# import function as f
# area = f.calculateArea(2)

JSON In Python

In [19]:
Gx = {}
Gx[3976] = {
    "name": "Mayur Pai",
    "email": "mbantwal@galaxe.com"
}

Gx[3985] = {
    "name": "Kavya",
    "email": "ksrinivasa@galaxe.com"
}

print(Gx)
print(Gx[3976])

import json
print(json.dumps(Gx))

with open("C://Users//mbantwal//GitLab//Gx//Python-Workspace//Galaxe-Data.txt", "w") as filename:
    filename.write(json.dumps(Gx))

with open("C://Users//mbantwal//GitLab//Gx//Python-Workspace//Galaxe-Data.txt", "r") as filename:
    print(filename.read())

# Or

filename = open("C://Users//mbantwal//GitLab//Gx//Python-Workspace//Galaxe-Data.txt", "r")
fileOutput = filename.read()
print(fileOutput)

print(json.loads(fileOutput))

type(Gx)

print(Gx[3976]["name"])

for person in Gx:
    print(Gx[person])

{3976: {'name': 'Mayur Pai', 'email': 'mbantwal@galaxe.com'}, 3985: {'name': 'Kavya', 'email': 'ksrinivasa@galaxe.com'}}
{'name': 'Mayur Pai', 'email': 'mbantwal@galaxe.com'}
{"3976": {"name": "Mayur Pai", "email": "mbantwal@galaxe.com"}, "3985": {"name": "Kavya", "email": "ksrinivasa@galaxe.com"}}
{"3976": {"name": "Mayur Pai", "email": "mbantwal@galaxe.com"}, "3985": {"name": "Kavya", "email": "ksrinivasa@galaxe.com"}}
{"3976": {"name": "Mayur Pai", "email": "mbantwal@galaxe.com"}, "3985": {"name": "Kavya", "email": "ksrinivasa@galaxe.com"}}
{'3976': {'name': 'Mayur Pai', 'email': 'mbantwal@galaxe.com'}, '3985': {'name': 'Kavya', 'email': 'ksrinivasa@galaxe.com'}}
Mayur Pai
{'name': 'Mayur Pai', 'email': 'mbantwal@galaxe.com'}
{'name': 'Kavya', 'email': 'ksrinivasa@galaxe.com'}


File Write In Python

In [20]:
filename = open("C://Users//mbantwal//GitLab//Gx//Python-Workspace//Galaxe-Data.txt", "w")
filename.write("My Name Is Mayur Pai B H")
filename.close()

File Read In Python

In [21]:
filenameRead = open("C://Users//mbantwal//GitLab//Gx//Python-Workspace//Input.txt", "r")
# print(filename.read())

for line in filenameRead:
    tokens = line.split(' ')
    print(len(tokens))
    print(str(tokens))
    print(line)


filenameRead.close()


11
['{"3976":', '{"name":', '"Mayur', 'Pai",', '"email":', '"mbantwal@galaxe.com"},', '"3985":', '{"name":', '"Kavya",', '"email":', '"ksrinivasa@galaxe.com"}}']
{"3976": {"name": "Mayur Pai", "email": "mbantwal@galaxe.com"}, "3985": {"name": "Kavya", "email": "ksrinivasa@galaxe.com"}}


In [22]:
def freq(fileRead):
	str_list = fileRead.split()
	unique_words = set(str_list)
	
	for words in unique_words :
		print('Frequency of ', words , 'is :', str_list.count(words))

if __name__ == "__main__":
	filenameRead = open("C://Users//mbantwal//GitLab//Gx//Python-Workspace//Input.txt", "r")
	freq(filenameRead.read())


Frequency of  "mbantwal@galaxe.com"}, is : 1
Frequency of  "3985": is : 1
Frequency of  {"3976": is : 1
Frequency of  "ksrinivasa@galaxe.com"}} is : 1
Frequency of  "email": is : 2
Frequency of  "Kavya", is : 1
Frequency of  {"name": is : 2
Frequency of  Pai", is : 1
Frequency of  "Mayur is : 1


In [23]:
def calculateSqaureArea(a):
    return a*a

if __name__ == "__main__":
    print(calculateSqaureArea(2))

4


Exceptions In Python

In [24]:
x = int(input("Enter First Number: "))
y = int(input("Enter Second Number: "))
try:
    z = x / y
# except Exception as e:
#     print("Exception Occurred: ", e)
#     z = "None"

except ZeroDivisionError as e:
    print("Exception Type:", e)

except Exception as e:
    print("Exception Type:", type(e).__name__)

print(z)

0.6666666666666666


Class And Objects In Python

In [25]:
class Human:
    def __init__(self, name, salary):
        self.name = name
        self.salary = salary

    def do_word(self):
        if self.name == "Mayur":
            print("Hey", self.name)
        elif self.name == "":
            print("Hey Ghost 👻")

    def speak(self):
        if self.name == "":
            print("Can't You Speak?")
        else:
            print(self.name,"How Are You?")

mayur = Human("Mayur", 33500)
mayur.do_word()
mayur.speak()

Hey Mayur
Mayur How Are You?


Inheritance In Python

In [26]:
class Vehicle:
    def general_usage(self):
        print("general use: transporation")

class Car(Vehicle):
    def __init__(self):
        print("I'm car")
        self.wheels = 4
        self.has_roof = True

    def specific_usage(self):
        self.general_usage()
        print("specific use: commute to work, vacation with family")

class MotorCycle(Vehicle):
    def __init__(self):
        print("I'm motor cycle")
        self.wheels = 2
        self.has_roof = False

    def specific_usage(self):
        self.general_usage()
        print("specific use: road trip, racing")

c = Car()
m = MotorCycle()

print(isinstance(c,Car))
print(isinstance(c,MotorCycle))
print(issubclass(Car,MotorCycle))
print(issubclass(Car,Vehicle))

I'm car
I'm motor cycle
True
False
False
True


Multiple Inheritance In Python

In [27]:
class Father():
   def skills(self):
       print("gardening,programming")

class Mother():
   def skills(self):
       print("cooking,art")

class Child(Father,Mother):
    def skills(self):
        Father.skills(self)
        Mother.skills(self)
        print("sports")

c = Child()
c.skills()

gardening,programming
cooking,art
sports


Raise Exception And Finally In Python

In [28]:
class Accident(Exception):
    def __init__(self, msg):
        self.msg = msg

    def print_exception(self):
        print("User Defined Execption:", self.msg)


try:
    raise Accident("Crash Between Two Cars")
except Accident as e:
    e.print_exception()

def process_file():
   try:
       f=open("C://Users//mbantwal//GitLab//Gx//Python-Workspace//Input.txt")
       x=1/0
   except FileNotFoundError as e:
       print("inside except")
   finally:
       print("cleaning up file")
       f.close()

process_file()

User Defined Execption: Crash Between Two Cars
cleaning up file


ZeroDivisionError: division by zero

Iterators In Python

In [ ]:
class RemoteControl():
    def __init__(self):
        self.channels = ["HBO","cnn","abc","espn"]
        self.index = -1

    def __iter__(self):
        return self

    def __next__(self):
        self.index += 1
        if self.index == len(self.channels):
            raise StopIteration

        return self.channels[self.index]

r = RemoteControl()
itr=iter(r)
print(next(itr))
print(next(itr))
print(next(itr))
print(next(itr))
# print(next(itr))

HBO
cnn
abc
espn


Generators In Python

In [ ]:
def remote_control_next():
    yield "Mayur"
    yield "Pai"
    yield "B H"

itr = remote_control_next()
print(itr)
print(next(itr))
print(next(itr))
print(next(itr))

<generator object remote_control_next at 0x0000016F626FF8A0>
Mayur
Pai
B H


In [ ]:
def fib():
    a, b = 0, 1
    while True:
        yield a
        a, b = b, a+b

for f in fib():
    if f > 100:
        break
    print(f)

0
1
1
2
3
5
8
13
21
34
55
89


List Set Dict Comprehensions In Python

In [ ]:
numbers = [1, 2, 3, 4, 5, 6, 7]
print([i for i in numbers if i % 2 == 0])
print([i*i for i in numbers])


[2, 4, 6]
[1, 4, 9, 16, 25, 36, 49]


In [ ]:
s = set([1, 2, 3, 4, 5, 6, 7, 8, 9, 1])
print(s)

{1, 2, 3, 4, 5, 6, 7, 8, 9}


In [ ]:
print({i for i in [1, 2, 3, 4, 5, 6] if i % 2 != 0})


{1, 3, 5}


In [ ]:
cities = ["Mumbai", "Bangalore", "Paris"]
countries = ["India", "India", "France"]
z = zip(cities, countries)

for a in z:
    print(a)

dict = {city: country for city, country in zip(cities, countries)}
print(dict)


('Mumbai', 'India')
('Bangalore', 'India')
('Paris', 'France')
{'Mumbai': 'India', 'Bangalore': 'India', 'Paris': 'France'}


Sets and Frozen Sets In Python

In [ ]:
basketOne = {"Apple", "Orange", "Banana", "Apple", "Mango"}
basketTwo = {"Guava", "Water Melon", "Carrot", "Drum Stick", "Mango"}
print(type(basketOne))
print(basketOne)

a = set()
a.add(1)
a.add(2)
print(a)

unique_fruits = set(basketOne)
print(unique_fruits)

fs = frozenset(basketOne) # Add Not Allowed
print(fs) 

print(basketOne | basketTwo) # Union
print(basketOne & basketTwo) # Intersection
print(basketOne - basketTwo) # Set Difference
print(basketOne < basketTwo) # Subset


<class 'set'>
{'Orange', 'Banana', 'Mango', 'Apple'}
{1, 2}
{'Orange', 'Banana', 'Mango', 'Apple'}
frozenset({'Orange', 'Banana', 'Mango', 'Apple'})
{'Guava', 'Banana', 'Mango', 'Drum Stick', 'Water Melon', 'Apple', 'Carrot', 'Orange'}
{'Mango'}
{'Banana', 'Apple', 'Orange'}


Decorators In Python

In [ ]:
import time


def time_it(func):
    def wrapper_func(*args, **kwargs):
        start = time.time()
        result = func(*args, **kwargs)
        end = time.time()
        print(func.__name__ + " took " + str((end - start) * 1000) + " ms")
        # return result
    return wrapper_func


@time_it
def calc_square(array):
    sol = []
    for i in array:
        sol.append(i * i)
    return sol


@time_it
def calc_cube(array):
    sol = []
    for i in array:
        sol.append(i * i * i)
    return sol


numbers = range(1, 100000)
calc_square(numbers)
calc_cube(numbers)


calc_square took 18.297195434570312 ms
calc_cube took 29.861927032470703 ms


Multithreading In Python

In [ ]:
import time
import threading


def calc_square(array):
    sol = []
    for i in array:
        time.sleep(0, 2)
        sol.append(i * i)
    print(sol)


def calc_cube(array):
    sol = []
    for i in array:
        time.sleep(0, 2)
        sol.append(i * i * i)
    print(sol)

t = time.time()
numbers = range(1, 100000)
threadOne = threading.Thread(target=calc_square, args=(numbers, ))
threadTwo = threading.Thread(target=calc_cube, args=(numbers, ))

threadOne.start()
threadTwo.start()

threadOne.join()
threadTwo.join()

print("Done In: " + str(time.time() - t))


Exception in thread Exception in thread Thread-11 (calc_cube):
Traceback (most recent call last):
  File "c:\Users\mbantwal\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
Thread-10 (calc_square):
Traceback (most recent call last):
  File "c:\Users\mbantwal\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "c:\Users\mbantwal\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self.run()
  File "c:\Users\mbantwal\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\mbantwal\AppData\Local\Temp\ipykernel_25664\3666671006.py", line 8, in calc_square
    self._target(*self._args, **self._kwargs)
  File "C:\Users\mbantwal\AppData\Local\Temp\ipykernel_25664\3666671006.py", line 16, in calc_cube
TypeError: time.sleep() takes exactly one argument (2 given)
TypeError: time.sleep() 

Done In: 0.026936769485473633


Multiprocessing In Python

In [ ]:
import time
import multiprocessing

square_result = []

def calc_square(array):
    global square_result
    sol = []
    for i in array:
        square_result.append(i * i)
        sol.append(i * i)
    print(sol)


def calc_cube(array):
    sol = []
    for i in array:
        sol.append(i * i * i)
    print(sol)


if __name__ == "__main__":
    arr = [1, 2, 3, 4, 5]
    processOne = multiprocessing.Process(target=calc_square, args=(arr, ))
    processTwo = multiprocessing.Process(target=calc_cube, args=(arr, ))

    print(processOne)
    print(processTwo)
    
    processOne.start()
    processTwo.start()

    processOne.join()
    processTwo.join()

    print(square_result)

    # <Process name='Process-1' parent=55373 initial>
    # <Process name='Process-2' parent=55373 initial>
    # [1, 4, 9, 16, 25]
    # [1, 8, 27, 64, 125]
    # []

<Process name='Process-35' parent=25664 initial>
<Process name='Process-36' parent=25664 initial>
[]


Sharing Data Between Processes Using Array And Value

In [32]:
import time
import multiprocessing


def calc_square(array, square_result, val):
    val.value = 3.14
    for index, n in enumerate(array):
        square_result[index] = n * n


if __name__ == "__main__":
    arr = [1, 2, 3, 4, 5]
    square_result = multiprocessing.Array('i', len(arr))
    val = multiprocessing.Value('d', 0.0)
    processOne = multiprocessing.Process(
        target=calc_square, args=(arr, square_result, val))
    print(processOne)

    processOne.start()
    processOne.join()

    print(square_result[:]) 
    print(val.value) 
    # <Process name='Process-1' parent=55320 initial>
    # [1, 4, 9, 16, 25]
    # 3.14


<Process name='Process-9' parent=28948 initial>
[0, 0, 0, 0, 0]
0.0


In [33]:
import time
import multiprocessing


def calc_square(array, q):
    for i in array:
        q.put(i * i)


if __name__ == "__main__":
    arr = [1, 2, 3, 4, 5]
    q = multiprocessing.Queue()
    processOne = multiprocessing.Process(
        target=calc_square, args=(arr, q))
    print(processOne)

    processOne.start()
    processOne.join()

    while q.empty() is False:
        print(q.get())

    # <Process name='Process-1' parent=55942 initial>
    # 1
    # 4
    # 9
    # 16
    # 25


<Process name='Process-10' parent=28948 initial>


Multiprocessing Lock

In [40]:
import time
import multiprocessing


def withdraw(balance):
    for i in range(100):
        time.sleep(000.1)
        lock.acquire()
        balance.value = balance.value + 1
        lock.release()


def deposit(balance):
    for i in range(100):
        time.sleep(000.1)
        balance.value = balance.value - 1


if __name__ == "__main__":
    v_balance = multiprocessing.Value('i', 200)
    lock = multiprocessing.Lock()
    processOne = multiprocessing.Process(
        target=withdraw, args=(v_balance,))
    processTwo = multiprocessing.Process(
        target=deposit, args=(v_balance,))
    print(processOne)
    print(processTwo)

    processOne.start()
    processTwo.start()

    processOne.join()
    processTwo.join()

    print(v_balance.value)


<Process name='Process-23' parent=28948 initial>
<Process name='Process-24' parent=28948 initial>
200


Multiprocessing Pool (Map Reduce)

In [1]:
from multiprocessing import Pool
import time

def func(n):
    return n * n

if __name__ == "__main__":
    array = [1,2,3,4,5]
    p = Pool()
    t1 = time.time()
    result = p.map(func, array)
    print(time.time() - t1)

    result = []

    t2 = time.time()
    for i in array:
        result.append(func(i))
    print(time.time() - t2)

    # 0.02081775665283203
    # 1.2636184692382812e-05


Unit Testing In Python

In [2]:
def calc_square(arr):
    result = []
    for i in arr:
        result.append(i * i)
    return result


def test_calc_square():
    result = calc_square([1, 2, 3, 5])
    assert result == [1, 4, 9, 25]

# test_ rule for methods and file name
# python -m pytest -> Run The Test Files Recursively
# py.test -> Alternate Way
# py.test -v -> (Verbose : PASS/FAIL)


print(calc_square([1, 2, 3, 5]))


[1, 4, 9, 25]


Numpy

In [1]:
import numpy as np
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [10]:
import numpy as np
import time
import sys

l = range(1000)
print(sys.getsizeof(5) * len(l))

array = np.arange(1000)
print(array.itemsize)
print(array.size)
print(array.size * array.itemsize)

a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

print(a1 + a2)
print(a1[2])
print(a1.ndim)
print(a1.itemset)
print(a1.itemsize)


28000
4
1000
4000
[5 7 9]
3
1
<built-in method itemset of numpy.ndarray object at 0x00000133FABAFB70>
4


In [15]:
import numpy as np
arr = np.array([[1,2], [3,4], [5, 6]], dtype=np.float64)
print(arr.itemsize)
print(arr.itemset)
print(arr.size)
print(arr.shape)
print(arr.ndim)
print(arr)

8
<built-in method itemset of numpy.ndarray object at 0x00000133FF7BBB10>
6
(3, 2)
2
[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [34]:
import numpy as np
arr = np.array([[1,2], [3,4], [5, 6]], dtype=np.float64)
arr0 = np.zeros((3,4))
arr1 = np.ones((3,4))
print(arr0)
print(arr1)

np.arange(1,5)
np.linspace(1,2,3)

arr0.reshape(12,1)
print(arr0)

arr0.ravel()

arr.min()
arr.max()
arr.sum()
arr.sum(axis=0)
arr.sum(axis=1)
np.sqrt(arr)
np.std(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


1.707825127659933

In [56]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr[0:1, 2]
arr[0:1]

for row in arr:
    print(row)

for cell in arr.flat:
    print(cell)

a1 = np.arange(6).reshape(2,3)
a2 = np.arange(6,12).reshape(2,3)
print(np.vstack((a1,a2)))
print(np.hstack((a1,a2)))

np.vsplit(a1, 1)

a = np.arange(12).reshape(3, 4)
b = a > 5

print("Greater Than 5: ", a[b])

a[b] = -1
print(a)

[1 2 3]
[4 5 6]
[7 8 9]
1
2
3
4
5
6
7
8
9
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]
Greater Than 5:  [ 6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5 -1 -1]
 [-1 -1 -1 -1]]


nditer In Python

In [57]:
import numpy as np
a = np.arange(12).reshape(3,4)
a

for row in a:
    for cell in row:
        print(cell)


for cell in a.flatten():
    print(cell)

for x in np.nditer(a, order='C'):
    print(x)

for x in np.nditer(a, order='F'):
    print(x)

for x in np.nditer(a, flags=['external_loop'],order='F'):
    print(x)

for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = x * x

a

b = np.arange(3, 15, 4).reshape(3,1)
b

for x, y in np.nditer([a,b]):
    print (x,y)

0
1
2
3
4
5
6
7
8
9
10
11
0
1
2
3
4
5
6
7
8
9
10
11
0
1
2
3
4
5
6
7
8
9
10
11
0
4
8
1
5
9
2
6
10
3
7
11
[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]
0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
